### ISSUE TITLE
Selectize reorders original options ordering 

### ISSUE THREAD

**Issue by Gooliver2** [sanoma/django-arctic#344]
Selectize by default tries to find best matching (based on his opinion) and it reorders original ordering of options. 
There was couple issues opened in Selectize repo, they are closed but from last year seems like it still occurs. From discussion of [this issue](https://github.com/selectize/selectize.js/issues/218) we can see, that Selectize is made to have full of lists on front-end. 
But Arctic is "backend" framework and we do all configurations (including ordering) in backend, so I propose to disable this Selectize feature to be able to order options on backend easily.

**Comment by FritzHerbers** [comment]
@Gooliver2 , @mmarcos 
We have sorting via sortField not configured, as we would like to use the server-side order and notice a re-ordering.
I have seen several workarounds (since 2014) prior your latest merges and I am not sure of any of them are still valid/needed. 
Your merges are in my eyes not reflected in the documentation https://github.com/selectize/selectize.js/blob/master/docs/usage.md, as it does not explain how to keep server-side order.
What needs to be configured, to keep server-side order? Is searching and displaying in the server-side order supported ?
The sortField has a default '$order', but what happens when this property is not included in the select options ?
Hope you can help me.
